#!/bin/bash
#script to run the docker container 
docker run -it \
      --net=host \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --device=/dev/kfd \
      --device=/dev/dri \
      --group-add video \
      --ipc=host \
      --shm-size 8G \
      -v ./:/work \
      plant_pipeline:latest


