#!/bin/bash
#script to run the docker container 
# docker run -it \
#       --net=host \
#       --cap-add=SYS_PTRACE \
#       --security-opt seccomp=unconfined \
#       --device=/dev/kfd \
#       --device=/dev/dri \
#       --group-add video \
#       --ipc=host \
#       --shm-size 8G \
#       -v ./:/work \
#       -v /tmp/.X11-unix:/tmp/.X11-unix \
#       -e DISPLAY=$DISPLAY \
#       -e QT_X11_NO_MITSHM=1 \
#       sreeni:latest
docker run -it \
      --net=host \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --device=/dev/kfd \
      --device=/dev/dri \
      --group-add video \
      --ipc=host \
      --shm-size 8G \
      -v ./:/work \
      -v /tmp/.X11-unix:/tmp/.X11-unix \
      -e DISPLAY=$DISPLAY \
      sreeni:latest


